// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city_data/city.proto

package com.doo360.crm.model;

public final class CityListProto {
	private CityListProto() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface CityOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required string name = 1;
		boolean hasName();

		String getName();

		// required int32 type = 2;
		boolean hasType();

		int getType();

		// required int32 belongTo = 3;
		boolean hasBelongTo();

		int getBelongTo();

		// required string pinyin = 4;
		boolean hasPinyin();

		String getPinyin();

		// required string code = 5;
		boolean hasCode();

		String getCode();
	}

	public static final class City extends com.google.protobuf.GeneratedMessage
			implements CityOrBuilder {
		// Use City.newBuilder() to construct.
		private City(Builder builder) {
			super(builder);
		}

		private City(boolean noInit) {
		}

		private static final City defaultInstance;

		public static City getDefaultInstance() {
			return defaultInstance;
		}

		public City getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.doo360.crm.model.CityListProto.internal_static_model_City_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.doo360.crm.model.CityListProto.internal_static_model_City_fieldAccessorTable;
		}

		private int bitField0_;
		// required string name = 1;
		public static final int NAME_FIELD_NUMBER = 1;
		private java.lang.Object name_;

		public boolean hasName() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					name_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required int32 type = 2;
		public static final int TYPE_FIELD_NUMBER = 2;
		private int type_;

		public boolean hasType() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public int getType() {
			return type_;
		}

		// required int32 belongTo = 3;
		public static final int BELONGTO_FIELD_NUMBER = 3;
		private int belongTo_;

		public boolean hasBelongTo() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public int getBelongTo() {
			return belongTo_;
		}

		// required string pinyin = 4;
		public static final int PINYIN_FIELD_NUMBER = 4;
		private java.lang.Object pinyin_;

		public boolean hasPinyin() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public String getPinyin() {
			java.lang.Object ref = pinyin_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					pinyin_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getPinyinBytes() {
			java.lang.Object ref = pinyin_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				pinyin_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string code = 5;
		public static final int CODE_FIELD_NUMBER = 5;
		private java.lang.Object code_;

		public boolean hasCode() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public String getCode() {
			java.lang.Object ref = code_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					code_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getCodeBytes() {
			java.lang.Object ref = code_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				code_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			name_ = "";
			type_ = 0;
			belongTo_ = 0;
			pinyin_ = "";
			code_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasBelongTo()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasPinyin()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasCode()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, type_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, belongTo_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getPinyinBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getCodeBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, type_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, belongTo_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						4, getPinyinBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getCodeBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.doo360.crm.model.CityListProto.City parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.City parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				com.doo360.crm.model.CityListProto.City prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.doo360.crm.model.CityListProto.CityOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.doo360.crm.model.CityListProto.internal_static_model_City_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.doo360.crm.model.CityListProto.internal_static_model_City_fieldAccessorTable;
			}

			// Construct using
			// com.doo360.crm.model.CityListProto.City.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				name_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				type_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				belongTo_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				pinyin_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				code_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.doo360.crm.model.CityListProto.City.getDescriptor();
			}

			public com.doo360.crm.model.CityListProto.City getDefaultInstanceForType() {
				return com.doo360.crm.model.CityListProto.City
						.getDefaultInstance();
			}

			public com.doo360.crm.model.CityListProto.City build() {
				com.doo360.crm.model.CityListProto.City result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.doo360.crm.model.CityListProto.City buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				com.doo360.crm.model.CityListProto.City result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public com.doo360.crm.model.CityListProto.City buildPartial() {
				com.doo360.crm.model.CityListProto.City result = new com.doo360.crm.model.CityListProto.City(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.name_ = name_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.type_ = type_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.belongTo_ = belongTo_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.pinyin_ = pinyin_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.code_ = code_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.doo360.crm.model.CityListProto.City) {
					return mergeFrom((com.doo360.crm.model.CityListProto.City) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					com.doo360.crm.model.CityListProto.City other) {
				if (other == com.doo360.crm.model.CityListProto.City
						.getDefaultInstance())
					return this;
				if (other.hasName()) {
					setName(other.getName());
				}
				if (other.hasType()) {
					setType(other.getType());
				}
				if (other.hasBelongTo()) {
					setBelongTo(other.getBelongTo());
				}
				if (other.hasPinyin()) {
					setPinyin(other.getPinyin());
				}
				if (other.hasCode()) {
					setCode(other.getCode());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasName()) {

					return false;
				}
				if (!hasType()) {

					return false;
				}
				if (!hasBelongTo()) {

					return false;
				}
				if (!hasPinyin()) {

					return false;
				}
				if (!hasCode()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						name_ = input.readBytes();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						type_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						belongTo_ = input.readInt32();
						break;
					}
					case 34: {
						bitField0_ |= 0x00000008;
						pinyin_ = input.readBytes();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						code_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string name = 1;
			private java.lang.Object name_ = "";

			public boolean hasName() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				name_ = value;
				onChanged();
				return this;
			}

			public Builder clearName() {
				bitField0_ = (bitField0_ & ~0x00000001);
				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			void setName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				name_ = value;
				onChanged();
			}

			// required int32 type = 2;
			private int type_;

			public boolean hasType() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public int getType() {
				return type_;
			}

			public Builder setType(int value) {
				bitField0_ |= 0x00000002;
				type_ = value;
				onChanged();
				return this;
			}

			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000002);
				type_ = 0;
				onChanged();
				return this;
			}

			// required int32 belongTo = 3;
			private int belongTo_;

			public boolean hasBelongTo() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public int getBelongTo() {
				return belongTo_;
			}

			public Builder setBelongTo(int value) {
				bitField0_ |= 0x00000004;
				belongTo_ = value;
				onChanged();
				return this;
			}

			public Builder clearBelongTo() {
				bitField0_ = (bitField0_ & ~0x00000004);
				belongTo_ = 0;
				onChanged();
				return this;
			}

			// required string pinyin = 4;
			private java.lang.Object pinyin_ = "";

			public boolean hasPinyin() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public String getPinyin() {
				java.lang.Object ref = pinyin_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					pinyin_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setPinyin(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				pinyin_ = value;
				onChanged();
				return this;
			}

			public Builder clearPinyin() {
				bitField0_ = (bitField0_ & ~0x00000008);
				pinyin_ = getDefaultInstance().getPinyin();
				onChanged();
				return this;
			}

			void setPinyin(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000008;
				pinyin_ = value;
				onChanged();
			}

			// required string code = 5;
			private java.lang.Object code_ = "";

			public boolean hasCode() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public String getCode() {
				java.lang.Object ref = code_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					code_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setCode(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				code_ = value;
				onChanged();
				return this;
			}

			public Builder clearCode() {
				bitField0_ = (bitField0_ & ~0x00000010);
				code_ = getDefaultInstance().getCode();
				onChanged();
				return this;
			}

			void setCode(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				code_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:model.City)
		}

		static {
			defaultInstance = new City(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:model.City)
	}

	public interface CityListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .model.City city = 1;
		java.util.List<com.doo360.crm.model.CityListProto.City> getCityList();

		com.doo360.crm.model.CityListProto.City getCity(int index);

		int getCityCount();

		java.util.List<? extends com.doo360.crm.model.CityListProto.CityOrBuilder> getCityOrBuilderList();

		com.doo360.crm.model.CityListProto.CityOrBuilder getCityOrBuilder(
				int index);
	}

	public static final class CityList extends
			com.google.protobuf.GeneratedMessage implements CityListOrBuilder {
		// Use CityList.newBuilder() to construct.
		private CityList(Builder builder) {
			super(builder);
		}

		private CityList(boolean noInit) {
		}

		private static final CityList defaultInstance;

		public static CityList getDefaultInstance() {
			return defaultInstance;
		}

		public CityList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.doo360.crm.model.CityListProto.internal_static_model_CityList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.doo360.crm.model.CityListProto.internal_static_model_CityList_fieldAccessorTable;
		}

		// repeated .model.City city = 1;
		public static final int CITY_FIELD_NUMBER = 1;
		private java.util.List<com.doo360.crm.model.CityListProto.City> city_;

		public java.util.List<com.doo360.crm.model.CityListProto.City> getCityList() {
			return city_;
		}

		public java.util.List<? extends com.doo360.crm.model.CityListProto.CityOrBuilder> getCityOrBuilderList() {
			return city_;
		}

		public int getCityCount() {
			return city_.size();
		}

		public com.doo360.crm.model.CityListProto.City getCity(int index) {
			return city_.get(index);
		}

		public com.doo360.crm.model.CityListProto.CityOrBuilder getCityOrBuilder(
				int index) {
			return city_.get(index);
		}

		private void initFields() {
			city_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getCityCount(); i++) {
				if (!getCity(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < city_.size(); i++) {
				output.writeMessage(1, city_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < city_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, city_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.doo360.crm.model.CityListProto.CityList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.doo360.crm.model.CityListProto.CityList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				com.doo360.crm.model.CityListProto.CityList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.doo360.crm.model.CityListProto.CityListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.doo360.crm.model.CityListProto.internal_static_model_CityList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.doo360.crm.model.CityListProto.internal_static_model_CityList_fieldAccessorTable;
			}

			// Construct using
			// com.doo360.crm.model.CityListProto.CityList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getCityFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (cityBuilder_ == null) {
					city_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					cityBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.doo360.crm.model.CityListProto.CityList
						.getDescriptor();
			}

			public com.doo360.crm.model.CityListProto.CityList getDefaultInstanceForType() {
				return com.doo360.crm.model.CityListProto.CityList
						.getDefaultInstance();
			}

			public com.doo360.crm.model.CityListProto.CityList build() {
				com.doo360.crm.model.CityListProto.CityList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.doo360.crm.model.CityListProto.CityList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				com.doo360.crm.model.CityListProto.CityList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public com.doo360.crm.model.CityListProto.CityList buildPartial() {
				com.doo360.crm.model.CityListProto.CityList result = new com.doo360.crm.model.CityListProto.CityList(
						this);
				int from_bitField0_ = bitField0_;
				if (cityBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						city_ = java.util.Collections.unmodifiableList(city_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.city_ = city_;
				} else {
					result.city_ = cityBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.doo360.crm.model.CityListProto.CityList) {
					return mergeFrom((com.doo360.crm.model.CityListProto.CityList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					com.doo360.crm.model.CityListProto.CityList other) {
				if (other == com.doo360.crm.model.CityListProto.CityList
						.getDefaultInstance())
					return this;
				if (cityBuilder_ == null) {
					if (!other.city_.isEmpty()) {
						if (city_.isEmpty()) {
							city_ = other.city_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureCityIsMutable();
							city_.addAll(other.city_);
						}
						onChanged();
					}
				} else {
					if (!other.city_.isEmpty()) {
						if (cityBuilder_.isEmpty()) {
							cityBuilder_.dispose();
							cityBuilder_ = null;
							city_ = other.city_;
							bitField0_ = (bitField0_ & ~0x00000001);
							cityBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getCityFieldBuilder()
									: null;
						} else {
							cityBuilder_.addAllMessages(other.city_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getCityCount(); i++) {
					if (!getCity(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						com.doo360.crm.model.CityListProto.City.Builder subBuilder = com.doo360.crm.model.CityListProto.City
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addCity(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .model.City city = 1;
			private java.util.List<com.doo360.crm.model.CityListProto.City> city_ = java.util.Collections
					.emptyList();

			private void ensureCityIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					city_ = new java.util.ArrayList<com.doo360.crm.model.CityListProto.City>(
							city_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.doo360.crm.model.CityListProto.City, com.doo360.crm.model.CityListProto.City.Builder, com.doo360.crm.model.CityListProto.CityOrBuilder> cityBuilder_;

			public java.util.List<com.doo360.crm.model.CityListProto.City> getCityList() {
				if (cityBuilder_ == null) {
					return java.util.Collections.unmodifiableList(city_);
				} else {
					return cityBuilder_.getMessageList();
				}
			}

			public int getCityCount() {
				if (cityBuilder_ == null) {
					return city_.size();
				} else {
					return cityBuilder_.getCount();
				}
			}

			public com.doo360.crm.model.CityListProto.City getCity(int index) {
				if (cityBuilder_ == null) {
					return city_.get(index);
				} else {
					return cityBuilder_.getMessage(index);
				}
			}

			public Builder setCity(int index,
					com.doo360.crm.model.CityListProto.City value) {
				if (cityBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureCityIsMutable();
					city_.set(index, value);
					onChanged();
				} else {
					cityBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setCity(
					int index,
					com.doo360.crm.model.CityListProto.City.Builder builderForValue) {
				if (cityBuilder_ == null) {
					ensureCityIsMutable();
					city_.set(index, builderForValue.build());
					onChanged();
				} else {
					cityBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addCity(com.doo360.crm.model.CityListProto.City value) {
				if (cityBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureCityIsMutable();
					city_.add(value);
					onChanged();
				} else {
					cityBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addCity(int index,
					com.doo360.crm.model.CityListProto.City value) {
				if (cityBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureCityIsMutable();
					city_.add(index, value);
					onChanged();
				} else {
					cityBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addCity(
					com.doo360.crm.model.CityListProto.City.Builder builderForValue) {
				if (cityBuilder_ == null) {
					ensureCityIsMutable();
					city_.add(builderForValue.build());
					onChanged();
				} else {
					cityBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addCity(
					int index,
					com.doo360.crm.model.CityListProto.City.Builder builderForValue) {
				if (cityBuilder_ == null) {
					ensureCityIsMutable();
					city_.add(index, builderForValue.build());
					onChanged();
				} else {
					cityBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllCity(
					java.lang.Iterable<? extends com.doo360.crm.model.CityListProto.City> values) {
				if (cityBuilder_ == null) {
					ensureCityIsMutable();
					super.addAll(values, city_);
					onChanged();
				} else {
					cityBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearCity() {
				if (cityBuilder_ == null) {
					city_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					cityBuilder_.clear();
				}
				return this;
			}

			public Builder removeCity(int index) {
				if (cityBuilder_ == null) {
					ensureCityIsMutable();
					city_.remove(index);
					onChanged();
				} else {
					cityBuilder_.remove(index);
				}
				return this;
			}

			public com.doo360.crm.model.CityListProto.City.Builder getCityBuilder(
					int index) {
				return getCityFieldBuilder().getBuilder(index);
			}

			public com.doo360.crm.model.CityListProto.CityOrBuilder getCityOrBuilder(
					int index) {
				if (cityBuilder_ == null) {
					return city_.get(index);
				} else {
					return cityBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends com.doo360.crm.model.CityListProto.CityOrBuilder> getCityOrBuilderList() {
				if (cityBuilder_ != null) {
					return cityBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(city_);
				}
			}

			public com.doo360.crm.model.CityListProto.City.Builder addCityBuilder() {
				return getCityFieldBuilder().addBuilder(
						com.doo360.crm.model.CityListProto.City
								.getDefaultInstance());
			}

			public com.doo360.crm.model.CityListProto.City.Builder addCityBuilder(
					int index) {
				return getCityFieldBuilder().addBuilder(
						index,
						com.doo360.crm.model.CityListProto.City
								.getDefaultInstance());
			}

			public java.util.List<com.doo360.crm.model.CityListProto.City.Builder> getCityBuilderList() {
				return getCityFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.doo360.crm.model.CityListProto.City, com.doo360.crm.model.CityListProto.City.Builder, com.doo360.crm.model.CityListProto.CityOrBuilder> getCityFieldBuilder() {
				if (cityBuilder_ == null) {
					cityBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.doo360.crm.model.CityListProto.City, com.doo360.crm.model.CityListProto.City.Builder, com.doo360.crm.model.CityListProto.CityOrBuilder>(
							city_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					city_ = null;
				}
				return cityBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:model.CityList)
		}

		static {
			defaultInstance = new CityList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:model.CityList)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_model_City_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_model_City_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_model_CityList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_model_CityList_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\024city_data/city.proto\022\005model\"R\n\004City\022\014\n"
				+ "\004name\030\001 \002(\t\022\014\n\004type\030\002 \002(\005\022\020\n\010belongTo\030\003 "
				+ "\002(\005\022\016\n\006pinyin\030\004 \002(\t\022\014\n\004code\030\005 \002(\t\"%\n\010Cit"
				+ "yList\022\031\n\004city\030\001 \003(\0132\013.model.CityB*\n\031com."
				+ "doo360.crm.modelB\rCityListProto" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_model_City_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_model_City_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_model_City_descriptor,
						new java.lang.String[] { "Name", "Type", "BelongTo",
								"Pinyin", "Code", },
						com.doo360.crm.model.CityListProto.City.class,
						com.doo360.crm.model.CityListProto.City.Builder.class);
				internal_static_model_CityList_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_model_CityList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_model_CityList_descriptor,
						new java.lang.String[] { "City", },
						com.doo360.crm.model.CityListProto.CityList.class,
						com.doo360.crm.model.CityListProto.CityList.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
